In [6]:
import kagglehub
import pandas as pd
import numpy as np
import os

## Descarga de datos con Kaggle

In [2]:
# Download latest version
path = kagglehub.dataset_download("bandrehc/lima-restaurant-review")

print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Downloading from https://www.kaggle.com/api/v1/datasets/download/bandrehc/lima-restaurant-review?dataset_version_number=2...

100%|██████████| 27.7M/27.7M [00:03<00:00, 9.18MB/s]

Extracting files...

Path to dataset files: C:\Users\Miguel\.cache\kagglehub\datasets\bandrehc\lima-restaurant-review\versions\2

In [14]:
archivo1= os.path.join(path, 'Lima_Restaurants_2025_08_13.csv')

reviews = pd.read_csv(archivo1)

reviews.head()

,id_review,caption,relative_date,review_date,retrieval_date,rating,username,n_review_user,url_user,url_place,id_place
0,ChZDSUhNMG9nS0VJQ0FnSUNVLV9HNEJ3EAE,NaN,Hace 6 años,2019-08-14 02:55:32.748162,2025-08-12 02:55:32.748162,5,Eduardo Rentería,0,https://www.google.com/maps/contrib/1146375908...,https://www.google.com/maps/place/?q=place_id:...,ChIJ--Rcshq4BZERPIDegz6p5-o
1,ChZDSUhNMG9nS0VJQ0FnSURrb2FUZk5REAE,NaN,Hace 6 años,2019-08-14 02:55:32.748573,2025-08-12 02:55:32.748573,5,Margot Menacho,0,https://www.google.com/maps/contrib/1152404922...,https://www.google.com/maps/place/?q=place_id:...,ChIJ--Rcshq4BZERPIDegz6p5-o
2,ChdDSUhNMG9nS0VJQ0FnSUNFdEtlbW93RRAB,NaN,Hace 6 años,2019-08-14 02:55:32.749164,2025-08-12 02:55:32.749164,5,Johrdan Davila Ruiz,2,https://www.google.com/maps/contrib/1146353983...,https://www.google.com/maps/place/?q=place_id:...,ChIJ--Rcshq4BZERPIDegz6p5-o
3,ChdDSUhNMG9nS0VJQ0FnSUNFNE5PYV9BRRAB,"Sirven menú variado de lunes a viernes, en bas...",Hace 6 años,2019-08-14 02:55:32.749667,2025-08-12 02:55:32.749667,3,Luis Anticona,31,https://www.google.com/maps/contrib/1029463912...,https://www.google.com/maps/place/?q=place_id:...,ChIJ--Rcshq4BZERPIDegz6p5-o
4,ChZDSUhNMG9nS0VJQ0FnSURZNzV6akRREAE,Todo muy rico peeo caro,Hace 6 años,2019-08-14 02:55:32.750200,2025-08-12 02:55:32.750200,4,Adrian Rebaza,67,https://www.google.com/maps/contrib/1063973783...,https://www.google.com/maps/place/?q=place_id:...,ChIJ--Rcshq4BZERPIDegz6p5-o

In [15]:
archivo2= os.path.join(path, 'restaurant_metadata.csv')

places= pd.read_csv(archivo2)

places.head()

,id_place,url_place,title,category,address,phoneNumber,completePhoneNumber,domain,url,stars,reviews,district,lat,long
0,ChIJ41RbR-W3BZERtC40lE27kJI,https://www.google.com/maps/place/?q=place_id:...,La 73,Restaurante,"Av. el Sol 175, Barranco 15063",(01) 2470780,+51 1 2470780,instagram.com,https://instagram.com/la73_barranco?utm_medium...,4.4,1741.0,Barranco,-12.139661,-77.023216
1,ChIJq6DzbfK3BZERzmnElUR7PUM,https://www.google.com/maps/place/?q=place_id:...,Pan Sal Aire,Restaurante,"Av. Almte. Miguel Grau 320, , Lima, Barranco 1...",951 118 993,+51 951 118 993,delivery.pansalaire.pe,https://delivery.pansalaire.pe/,4.6,2229.0,Barranco,-12.148280,-77.021087
2,ChIJQwRnc-23BZERpyhQvLJVMTQ,https://www.google.com/maps/place/?q=place_id:...,Restaurante Javier,Restaurante peruano,"Bajada de Baños 408, Barranco 15063",984 799 808,+51 984 799 808,www.restaurantejavier.pe,https://www.restaurantejavier.pe/,4.3,6810.0,Barranco,-12.149831,-77.023228
3,ChIJbYWvNb63BZER3Mb9WXTrobo,https://www.google.com/maps/place/?q=place_id:...,Nuestro Bistro,Restaurante,"Jr. Colina 107, Barranco 15063",948 721 346,+51 948 721 346,www.instagram.com,https://www.instagram.com/nuestro_bistro/,4.9,122.0,Barranco,-12.145981,-77.022046
4,ChIJQWG-5e63BZERioL90gT0vZ8,https://www.google.com/maps/place/?q=place_id:...,Cala Restaurante & Lounge,Restaurante,"Circuito de Playas, Barranco 15063",998 247 326,+51 998 247 326,NaN,NaN,4.4,8900.0,Barranco,-12.144648,-77.025753

## Cruce de datos

In [16]:
df = reviews.merge(
    places,
    on="id_place",
    how="left"
)

df.head()

,id_review,caption,relative_date,review_date,retrieval_date,rating,username,n_review_user,url_user,url_place_x,...,address,phoneNumber,completePhoneNumber,domain,url,stars,reviews,district,lat,long
0,ChZDSUhNMG9nS0VJQ0FnSUNVLV9HNEJ3EAE,NaN,Hace 6 años,2019-08-14 02:55:32.748162,2025-08-12 02:55:32.748162,5,Eduardo Rentería,0,https://www.google.com/maps/contrib/1146375908...,https://www.google.com/maps/place/?q=place_id:...,...,"Doña Virginia 105, Santiago de Surco 15049",(01) 7730584,+51 1 7730584,NaN,NaN,4.3,29.0,Surco,-12.140145,-76.999662
1,ChZDSUhNMG9nS0VJQ0FnSURrb2FUZk5REAE,NaN,Hace 6 años,2019-08-14 02:55:32.748573,2025-08-12 02:55:32.748573,5,Margot Menacho,0,https://www.google.com/maps/contrib/1152404922...,https://www.google.com/maps/place/?q=place_id:...,...,"Doña Virginia 105, Santiago de Surco 15049",(01) 7730584,+51 1 7730584,NaN,NaN,4.3,29.0,Surco,-12.140145,-76.999662
2,ChdDSUhNMG9nS0VJQ0FnSUNFdEtlbW93RRAB,NaN,Hace 6 años,2019-08-14 02:55:32.749164,2025-08-12 02:55:32.749164,5,Johrdan Davila Ruiz,2,https://www.google.com/maps/contrib/1146353983...,https://www.google.com/maps/place/?q=place_id:...,...,"Doña Virginia 105, Santiago de Surco 15049",(01) 7730584,+51 1 7730584,NaN,NaN,4.3,29.0,Surco,-12.140145,-76.999662
3,ChdDSUhNMG9nS0VJQ0FnSUNFNE5PYV9BRRAB,"Sirven menú variado de lunes a viernes, en bas...",Hace 6 años,2019-08-14 02:55:32.749667,2025-08-12 02:55:32.749667,3,Luis Anticona,31,https://www.google.com/maps/contrib/1029463912...,https://www.google.com/maps/place/?q=place_id:...,...,"Doña Virginia 105, Santiago de Surco 15049",(01) 7730584,+51 1 7730584,NaN,NaN,4.3,29.0,Surco,-12.140145,-76.999662
4,ChZDSUhNMG9nS0VJQ0FnSURZNzV6akRREAE,Todo muy rico peeo caro,Hace 6 años,2019-08-14 02:55:32.750200,2025-08-12 02:55:32.750200,4,Adrian Rebaza,67,https://www.google.com/maps/contrib/1063973783...,https://www.google.com/maps/place/?q=place_id:...,...,"Doña Virginia 105, Santiago de Surco 15049",(01) 7730584,+51 1 7730584,NaN,NaN,4.3,29.0,Surco,-12.140145,-76.999662